#LINEA = colectivos.dao.secuencial.LineaSecuencialDAO
#PARADA = colectivos.dao.secuencial.ParadaSecuencialDAO
#TRAMO = colectivos.dao.secuencial.TramoSecuencialDAO

LINEA = colectivos.dao.postgresql.LineaPostgresqlDAO
PARADA = colectivos.dao.postgresql.ParadaPostgresqlDAO
TRAMO = colectivos.dao.postgresql.TramoPostgresqlDAO